require:
  - rubocop-performance
  - rubocop-rspec

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageChain:
  Enabled: false
