name: Build

on: [push]

jobs:
  Build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Specs
      run: bundle exec rake
    - name: Check delta coverage
      run: bundle exec delta-simplecov-checks --sha ${{ github.sha }} --repository ${{ github.repository }}
      env:
        APP_SECRET: ${{ secrets.SECRET_KEY }}
        APP_ID: ${{ secrets.APP_ID }}
        APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
    - name: Coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage/
  Rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Rubocop
        run: bundle exec rubocop --parallel
